My first pull request
Kandy-Peter/hello-Microverse- pull request #1
Opened 2021-11-23 12:16 UTC by Kandy-Peter

2021-11-23 12:50 UTC, VanessaAoki requested changes
## STATUS: CHANGES REQUIRED :yellow_circle: 
Hi @Kandy-Peter, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### Project highlights:
- [x] Descriptive commits and correct use of the GitHub Flow :fire: 

## Required Changes ♻️
_Check the comments under the review._
- [ ] Besides those comments, keep in mind that your Pull Request (PR) should have a small summary of what was done in this branch, you can read more about it [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).

![so close](https://c.tenor.com/nMbdSNsg_jsAAAAC/the-simpsons-homer-simpson.gif)

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-23 12:50 UTC, VanessaAoki commented on README.md
> +![screenshot](./app_screenshot.png)
- [ ] Great job using Microverse's template. For this part, you should consider adding a screenshot from your project. This is how it looks right now:

![image](https://user-images.githubusercontent.com/66967274/143024537-9bd1eea9-40dd-4de4-a98f-2c388c171fa1.png)

2021-11-23 12:50 UTC, VanessaAoki commented on README.md
> +Additional description about the project and its features.
- [ ] Don't forget to edit this part as well, if you feel like there is nothing more to say, you should simply delete this line.

2021-11-23 12:50 UTC, VanessaAoki commented on README.md
> +-Linker
- [ ] This getting started looks a bit confusing. You should consider adding a more descriptive instruction, keep in mind that some people do not have any coding experience, so make it as simple and detailed as possible.

2021-11-23 12:50 UTC, VanessaAoki commented on README.md
> +👤 **Author1**
- [ ] Instead of having it as "Author1" why don't we change it to your actual name? I think it would look much better, don't you?

2021-11-23 12:50 UTC, VanessaAoki commented on .github/linters.yml
> +        run: npx stylelint "**/*.{css,scss}"
- [ ] Right now, there are no checks in your repo, this is because this pathing is not correct. Inside the `.github` folder, you should have another folder named `workflows`, and there is where the `linters.yml` file should be! You should consider fixing this so you get the checks running, this is how it looks right now:

![image](https://user-images.githubusercontent.com/66967274/143025906-687f2cf7-9603-48a5-8f19-2041631f1d36.png)

2021-11-23 13:56 UTC, Kandy-Peter commented on README.md
> +![screenshot](./app_screenshot.png)
I resolved the problem

2021-11-23 14:09 UTC, Kandy-Peter commented
Hi @VanessaAoki 
Thank you for your comments, they have helped me a lot and I hope I have met all the required points.

2021-11-24 06:44 UTC, Rustamxon7 approved these changes
## Hi @Kandy-Peter  👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

![image](https://user-images.githubusercontent.com/69011963/133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7.png)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-11-24 07:20 UTC, merged